apiVersion: batch/v1
kind: Job
metadata:
  name: adb-init
spec:
  template:
    spec:
      containers:
      - name: adb-init
        image: busybox
        command: ["sh scripts.sh"]
        volumeMounts:
          - name: axdb-root-password
            mountPath: "/etc/admin"
            readOnly: true
      volumes:
      - name: axdb-root-password
        secret:
          secretName: alexandria-db-root-password
          items:
          - key: password
            path: pwd
      restartPolicy: Never
  backoffLimit: 4