apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alexandria-db
  namespace: default
spec:
  entryPoints:
    other:
      address: ":8529"
  routes:
    - kind: Rule
      match: PathPrefix(`/ax`)
      services:
        - name: alexandria-db-ea
          port: 8529
  tls:
    certResolver: default