apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/nix`)
      services:
        - name: nginx-6db489d4b7-ckg5f
          port: 80