apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "alexandria-db"
  namespace: axdb
  labels:
    environment: production
    app: alexandria
    type: db
spec:
  mode: Cluster
  image: arangodb/arangodb:3.6.2
  environment: Production