baseURL = "/"
languageCode = "en-us"
title = "Alexandria Documentation"
theme = "book"
publishDir = "docs"

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/cloud-native-eam/alexandria"
  weight = 10